### ISSUE TITLE
VNC settings

### ISSUE THREAD

**Issue by ghost** [retspen/webvirtmgr#44]
I love the webvirtmgr.  For the users in my office that are die hard virt-manager users, is there a way to get the VNC to play nice across both?

On a VM created from webvirtmgr, a console session opens flawlessly.  From virt-manager, it asks for a password, but no password I've tried works.

On a VM created from virt-manager, a console session opens and prompts for ssh credentials from webvirtmgr (which is fine if that's the only option)

My issue is that I prefer to create the VMs in webvirtmgr, but thus far I'm not able to give console access to the virt-manager users.  Is there a way to get them to play nice together?
Thanks.

**Comment by thiagocpv** [comment]
I have the same problem when running over https.
Server disconnected (code: 1006)

**Comment by howels** [comment]
Same issue running over HTTPS, main site works but console connects are messed up. Interestingly I also get a timeout when I try to access console connections via DNS instead of the direct IP.

**Comment by Bandic007** [comment]
Hello all,
I know this project is long forgotten, but I am experiencing the same issue like @howels.
Over HTTPS everything else is working, except the noVNC. I have a domain name and when I try to access the system over the domain name, the noVNC is timing out. It is working when I use the IPaddress:port. I am using the WebVirtCloud project now, but the issue is the same and persists there too. Did any one of you found a solution to this?

**Comment by Bandic007** [comment]
I was not able to find info how to properly setup setup noVNC to use SSL.
Can you share me your settings.py file and explain me in brief what and where did you done and changed (if there are other files that needs additional changes) so that I can set it up and test?

Just FYI - I am using CloudFlare and the SSL certificate is not local on the host, but it is the cloudflare ssl that I am using. My setup is more specific and I don't know if it can work like that, but anyway - please, explain to me so that I can move to LetsEncrypt eventually in order to use the VNC over SSL!

Thank you very much!

**Comment by thiagocpv** [comment]
Hi @Bandic007 

See mey settings.py with the certificate.  My certificate file is stored at the same server that I am running webvirtcloud.

# WebVirtCloud settings
# Wobsock port
WS_PORT = 6080
# Websock host
WS_HOST = "panel.yourdomain.com"
# Websock public port
WS_PUBLIC_HOST = "panel.yourdomain.com"
# Websock SSL connection
#WS_CERT = "/etc/ssl/certificate.pem"
WS_CERT = "/etc/letsencrypt/live/panel.yourdomain.com/fullchain.pem"

**Comment by Bandic007** [comment]
I see but I am using CloudFlare and my SSL certificate is not locally stored on the host, but it is being offloaded on cloudfalre portal. I am using their share SSL cert... Maybe this is my problem?

**Comment by multfaciladm** [comment]
for sure it is your problem. The settings.py is looking for the cert locally.
